[project]
name = "local-geocode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.10",
    "flashtext>=2.7",
    "joblib>=1.4.2",
    "pandas>=1",
    "tqdm>=4.67.1",
    "uvicorn>=0.34.0",
]
